apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kotaj40sm-nodejs
  janus-idp.io/tekton: kotaj40sm-nodejs
  backstage.io/kubernetes-id: kotaj40sm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kotaj40sm-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
